The name of this dataset is "Current_Employee_Names__Salaries__and_Position_Titles". It represents the information about all the current employees of the City of Chicago, which includes their names(object), job titles(object), departments they worked for(object), their working status(full or part time, object) and their payment method(salary or hourly, object). Also, for salary paid employees, there is a annual salary(float64), and for hourly paid employees, there are typical hours they worked(float64) and their hourly rate payment(float64).

I obtained this dataset from the City of Chicago data portal.

URL: https://data.cityofchicago.org/Administration-Finance/Current-Employee-Names-Salaries-and-Position-Title/xzkq-xp2w.

License: The dataset is provided to the public by The City of Chicago. The City of Chicago doesn't responsible for the accuracy and completeness of the information, and could ask the user to stop using the data for any reason.

File size: 2.19 MB (2,296,961 bytes)

In [1]:
import pandas as pd
import bqplot
import numpy as np
import ipywidgets
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('/Users/CHENYX/590DV/Current_Employee_Names__Salaries__and_Position_Titles.csv')
data

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"ADRIANO, RACQUEL ANNE",PARAMEDIC,FIRE,F,Salary,NaN,72510.0,NaN
1,"AFFANEH, MAHIR A",POLICE OFFICER,POLICE,F,Salary,NaN,93354.0,NaN
2,"AFOENYI, PHYLLIS",TITLE V PROGRAM TRAINEE I,FAMILY & SUPPORT,P,Hourly,20.0,NaN,13.00
3,"AGAR, BULENT B",DEPUTY COMMISSIONER,WATER MGMNT,F,Salary,NaN,132972.0,NaN
4,"AGEE, LAWRENCE",POLICE OFFICER,POLICE,F,Salary,NaN,90024.0,NaN
5,"AGNEW, ANTONIO E",MOTOR TRUCK DRIVER,AVIATION,F,Hourly,40.0,NaN,37.45
6,"AGNEW, MELISSA M",SERGEANT,POLICE,F,Salary,NaN,111444.0,NaN
7,"AGOSTA, JOSEPH J",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,103932.0,NaN
8,"AGOSTINELLI, MICHAEL A",FIREFIGHTER (PER ARBITRATORS AWARD)-EMT,FIRE,F,Salary,NaN,107106.0,NaN
9,"AGOSTINI, LUIS R",ASST DIR,POLICE,F,Salary,NaN,95736.0,NaN
10,"AGOSTO, HECTOR I",POLICE OFFICER/EXPLSV DETECT K9 HNDLR,POLICE,F,Salary,NaN,94524.0,NaN
11,"AGREDANO, ELIAS",POLICE OFFICER,POLICE,F,Salary,NaN,48078.0,NaN
12,"AGREDANO, MARIO",BRIDGE OPERATOR,TRANSPORTN,F,Salary,NaN,67896.0,NaN
13,"AGRON, EDUARDO",SERGEANT,POLICE,F,Salary,NaN,122472.0,NaN
14,"AGRON, EDWIN",POLICE OFFICER,POLICE,F,Salary,NaN,90024.0,NaN
15,"AGSALUD, FERNAN S",SANITATION LABORER,STREETS & SAN,F,Hourly,40.0,NaN,40.78
16,"AGSALUD JR, JUANITO S",SANITATION LABORER,STREETS & SAN,F,Hourly,40.0,NaN,38.52
17,"AGUADA, GILBERT GLENN",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
18,"AGUAS, ALEX",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
19,"AGUAYO, BRAULIO",FIREFIGHTER-EMT,FIRE,F,Salary,NaN,89148.0,NaN
20,"AGUAYO, LUIS A",FIREFIGHTER-EMT,FIRE,F,Salary,NaN,92274.0,NaN
21,"AGUAYO, LUIS M",LABORER - APPRENTICE,WATER MGMNT,F,Hourly,40.0,NaN,34.98
22,"AGUAYO, MARIA G",ACCOUNTING TECHNICIAN II,FINANCE,F,Salary,NaN,47160.0,NaN
23,"AGUIAR, WILLIAM M",ADMINISTRATIVE DEPUTY,LAW,F,Salary,NaN,143976.0,NaN
24,"AGUILA, JUANITA",MOTOR TRUCK DRIVER,AVIATION,F,Hourly,40.0,NaN,37.45
25,"AGUILAR, ANDRIA",ALDERMANIC AIDE,CITY COUNCIL,P,Hourly,20.0,NaN,25.00
26,"AGUILAR, EFRAIN",SANITATION LABORER,STREETS & SAN,F,Hourly,40.0,NaN,38.52
27,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,111444.0,NaN
28,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
29,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,DAIS,F,Salary,NaN,118608.0,NaN
...,...,...,...,...,...,...,...,...
33672,"ZUNIGA, MILAGROS E",POOL MOTOR TRUCK DRIVER,AVIATION,F,Hourly,40.0,NaN,33.71
33673,"ZUNIGA, NOE",POLICE OFFICER,POLICE,F,Salary,NaN,80016.0,NaN
33674,"ZUNIGA, OSCAR",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
33675,"ZUNIGA, RONALD",POLICE OFFICER,POLICE,F,Salary,NaN,93354.0,NaN
33676,"ZUNIGA, THOMAS",GENERAL LABORER - DSS,STREETS & SAN,F,Hourly,40.0,NaN,25.95
33677,"ZUNIGA, VICENTE",FIREFIGHTER-EMT,FIRE,F,Salary,NaN,92274.0,NaN
33678,"ZUNO, ERIK",CONSTRUCTION LABORER,WATER MGMNT,F,Hourly,40.0,NaN,43.72
33679,"ZUPAN, BILL M",LIEUTENANT-EMT,FIRE,F,Salary,NaN,114324.0,NaN
33680,"ZUPANCIC, KELLY",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
33681,"ZURAWSKI, JEFFREY",FRM OF MACHINISTS - AUTOMOTIVE,DAIS,F,Hourly,40.0,NaN,51.43
33682,"ZURAWSKI, MAC Z",REFUSE COLLECTION COORD,STREETS & SAN,F,Salary,NaN,89772.0,NaN
33683,"ZURAWSKI, MARY E",POLICE OFFICER,POLICE,F,Salary,NaN,96060.0,NaN
33684,"ZUREK, FRANCIS",ELECTRICAL MECHANIC,PUBLIC SAFETY ADMIN,F,Hourly,40.0,NaN,49.35
33685,"ZUREK, MARY H",SENIOR PUBLIC INFORMATION OFFICER,FINANCE,F,Salary,NaN,96096.0,NaN
33686,"ZURITA, ADRIEL",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
33687,"ZVANJA, TINA M",LEGAL SECRETARY,LAW,F,Salary,NaN,85704.0,NaN
33688,"ZWARYCZ, THOMAS J",MOTOR TRUCK DRIVER,WATER MGMNT,F,Hourly,40.0,NaN,37.45
33689,"ZWIT, JEFFREY J",POLICE OFFICER,POLICE,F,Salary,NaN,90024.0,NaN
33690,"ZWOLFER, MATTHEW W",LIEUTENANT-EMT,FIRE,F,Salary,NaN,117996.0,NaN
33691,"ZYCH, LUKASZ",POLICE OFFICER,POLICE,F,Salary,NaN,72510.0,NaN
33692,"ZYCH, MATEUSZ",POLICE OFFICER,POLICE,F,Salary,NaN,80016.0,NaN
33693,"ZYDEK, BRYAN",POLICE OFFICER,POLICE,F,Salary,NaN,87006.0,NaN
33694,"ZYGMUNT, ARTUR",POLICE OFFICER,POLICE,F,Salary,NaN,72510.0,NaN
33695,"ZYGMUNT, DAWID",POLICE OFFICER,POLICE,F,Salary,NaN,80016.0,NaN
33696,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,80016.0,NaN
33697,"ZYLINSKA, KLAUDIA",POLICE OFFICER,POLICE,F,Salary,NaN,72510.0,NaN
33698,"ZYMANTAS, LAURA C",POLICE OFFICER,POLICE,F,Salary,NaN,76266.0,NaN
33699,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,90024.0,NaN
33700,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,93354.0,NaN
33701,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DAIS,F,Salary,NaN,126732.0,NaN

In [3]:
data.columns

Index(['Name', 'Job Titles', 'Department', 'Full or Part-Time',
       'Salary or Hourly', 'Typical Hours', 'Annual Salary', 'Hourly Rate'],
      dtype='object')

In [4]:
data.dtypes

Name                  object
Job Titles            object
Department            object
Full or Part-Time     object
Salary or Hourly      object
Typical Hours        float64
Annual Salary        float64
Hourly Rate          float64
dtype: object

In [5]:
salary = data[data['Salary or Hourly']=='Salary']
salary

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"ADRIANO, RACQUEL ANNE",PARAMEDIC,FIRE,F,Salary,NaN,72510.0,NaN
1,"AFFANEH, MAHIR A",POLICE OFFICER,POLICE,F,Salary,NaN,93354.0,NaN
3,"AGAR, BULENT B",DEPUTY COMMISSIONER,WATER MGMNT,F,Salary,NaN,132972.0,NaN
4,"AGEE, LAWRENCE",POLICE OFFICER,POLICE,F,Salary,NaN,90024.0,NaN
6,"AGNEW, MELISSA M",SERGEANT,POLICE,F,Salary,NaN,111444.0,NaN
7,"AGOSTA, JOSEPH J",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,103932.0,NaN
8,"AGOSTINELLI, MICHAEL A",FIREFIGHTER (PER ARBITRATORS AWARD)-EMT,FIRE,F,Salary,NaN,107106.0,NaN
9,"AGOSTINI, LUIS R",ASST DIR,POLICE,F,Salary,NaN,95736.0,NaN
10,"AGOSTO, HECTOR I",POLICE OFFICER/EXPLSV DETECT K9 HNDLR,POLICE,F,Salary,NaN,94524.0,NaN
11,"AGREDANO, ELIAS",POLICE OFFICER,POLICE,F,Salary,NaN,48078.0,NaN
12,"AGREDANO, MARIO",BRIDGE OPERATOR,TRANSPORTN,F,Salary,NaN,67896.0,NaN
13,"AGRON, EDUARDO",SERGEANT,POLICE,F,Salary,NaN,122472.0,NaN
14,"AGRON, EDWIN",POLICE OFFICER,POLICE,F,Salary,NaN,90024.0,NaN
17,"AGUADA, GILBERT GLENN",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
18,"AGUAS, ALEX",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
19,"AGUAYO, BRAULIO",FIREFIGHTER-EMT,FIRE,F,Salary,NaN,89148.0,NaN
20,"AGUAYO, LUIS A",FIREFIGHTER-EMT,FIRE,F,Salary,NaN,92274.0,NaN
22,"AGUAYO, MARIA G",ACCOUNTING TECHNICIAN II,FINANCE,F,Salary,NaN,47160.0,NaN
23,"AGUIAR, WILLIAM M",ADMINISTRATIVE DEPUTY,LAW,F,Salary,NaN,143976.0,NaN
27,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,111444.0,NaN
28,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
29,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,DAIS,F,Salary,NaN,118608.0,NaN
30,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,117072.0,NaN
31,"ABARCA, FRANCES J",POLICE OFFICER,POLICE,F,Salary,NaN,48078.0,NaN
34,"ABBATEMARCO, JAMES J",FIRE ENGINEER-EMT,FIRE,F,Salary,NaN,103350.0,NaN
35,"ABBATE, TERRY M",POLICE OFFICER,POLICE,F,Salary,NaN,93354.0,NaN
37,"ABBOTT, CARMELLA",POLICE OFFICER,POLICE,F,Salary,NaN,72510.0,NaN
38,"ABDALLAH, MARAM M",PARAMEDIC,FIRE,F,Salary,NaN,56304.0,NaN
39,"ABDALLAH, ZAID",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
40,"ABDELHADI, ABDALMAHD",POLICE OFFICER,POLICE,F,Salary,NaN,87006.0,NaN
...,...,...,...,...,...,...,...,...
33662,"ZUMARAS, ANTHONY R",PARAMEDIC,FIRE,F,Salary,NaN,76266.0,NaN
33664,"ZUMARRAGA, JOSHUA D",POLICE OFFICER,POLICE,F,Salary,NaN,68616.0,NaN
33665,"ZUMARRAGA, NATHAN W",POLICE OFFICER,POLICE,F,Salary,NaN,72510.0,NaN
33666,"ZUMBROCK, JOHN M",POLICE OFFICER,POLICE,F,Salary,NaN,90024.0,NaN
33670,"ZUNIGA, JUAN M",POLICE OFFICER,POLICE,F,Salary,NaN,90024.0,NaN
33671,"ZUNIGA, JURDON",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
33673,"ZUNIGA, NOE",POLICE OFFICER,POLICE,F,Salary,NaN,80016.0,NaN
33674,"ZUNIGA, OSCAR",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
33675,"ZUNIGA, RONALD",POLICE OFFICER,POLICE,F,Salary,NaN,93354.0,NaN
33677,"ZUNIGA, VICENTE",FIREFIGHTER-EMT,FIRE,F,Salary,NaN,92274.0,NaN
33679,"ZUPAN, BILL M",LIEUTENANT-EMT,FIRE,F,Salary,NaN,114324.0,NaN
33680,"ZUPANCIC, KELLY",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
33682,"ZURAWSKI, MAC Z",REFUSE COLLECTION COORD,STREETS & SAN,F,Salary,NaN,89772.0,NaN
33683,"ZURAWSKI, MARY E",POLICE OFFICER,POLICE,F,Salary,NaN,96060.0,NaN
33685,"ZUREK, MARY H",SENIOR PUBLIC INFORMATION OFFICER,FINANCE,F,Salary,NaN,96096.0,NaN
33686,"ZURITA, ADRIEL",POLICE OFFICER,POLICE,F,Salary,NaN,84054.0,NaN
33687,"ZVANJA, TINA M",LEGAL SECRETARY,LAW,F,Salary,NaN,85704.0,NaN
33689,"ZWIT, JEFFREY J",POLICE OFFICER,POLICE,F,Salary,NaN,90024.0,NaN
33690,"ZWOLFER, MATTHEW W",LIEUTENANT-EMT,FIRE,F,Salary,NaN,117996.0,NaN
33691,"ZYCH, LUKASZ",POLICE OFFICER,POLICE,F,Salary,NaN,72510.0,NaN
33692,"ZYCH, MATEUSZ",POLICE OFFICER,POLICE,F,Salary,NaN,80016.0,NaN
33693,"ZYDEK, BRYAN",POLICE OFFICER,POLICE,F,Salary,NaN,87006.0,NaN
33694,"ZYGMUNT, ARTUR",POLICE OFFICER,POLICE,F,Salary,NaN,72510.0,NaN
33695,"ZYGMUNT, DAWID",POLICE OFFICER,POLICE,F,Salary,NaN,80016.0,NaN
33696,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,80016.0,NaN
33697,"ZYLINSKA, KLAUDIA",POLICE OFFICER,POLICE,F,Salary,NaN,72510.0,NaN
33698,"ZYMANTAS, LAURA C",POLICE OFFICER,POLICE,F,Salary,NaN,76266.0,NaN
33699,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,90024.0,NaN
33700,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,93354.0,NaN
33701,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DAIS,F,Salary,NaN,126732.0,NaN

In [6]:
# group the dataset by "Department" and "Job Titles" to find the total annual salary value
total = salary.groupby(['Department','Job Titles'],as_index =False)['Annual Salary'].sum()
total

         Department                                 Job Titles  Annual Salary
0      ADMIN HEARNG                     ADMINISTRATIVE ASST II     1078020.00
1      ADMIN HEARNG                    ADMINISTRATIVE ASST III      299724.00
2      ADMIN HEARNG   ADMINISTRATIVE SERVICES OFFICER II EXCLD       96096.00
3      ADMIN HEARNG                      ADMINISTRATIVE SUPVSR       72744.00
4      ADMIN HEARNG            CUSTOMER ACCOUNT REPRESENTATIVE       64872.00
5      ADMIN HEARNG  DEPUTY DIR OF ADMINISTRATIVE ADJUDICATION      135624.00
6      ADMIN HEARNG                    DIR OF ADMINISTRATION I       96096.00
7      ADMIN HEARNG             DIR OF ADMINISTRATIVE HEARINGS      161112.00
8      ADMIN HEARNG                EXEC ADMINISTRATIVE ASST II       72744.00
9      ADMIN HEARNG                       FISCAL ADMINISTRATOR      121188.00
10     ADMIN HEARNG      MANAGER OF ADMINSTRATIVE ADJUDICATION      100620.00
11     ADMIN HEARNG          SENIOR ADMINISTRATIVE LAW OFFICER      398496.00
12     ADMIN HEARNG                     SENIOR HEARING OFFICER       72180.00
13     ADMIN HEARNG                                 STAFF ASST      286800.00
14    ANIMAL CONTRL   ADMINISTRATIVE SERVICES OFFICER II EXCLD       96096.00
15    ANIMAL CONTRL                         ANIMAL CARE AIDE I      321840.00
16    ANIMAL CONTRL                        ANIMAL CARE AIDE II      235200.00
17    ANIMAL CONTRL                          ANIMAL CARE CLERK       42960.00
18    ANIMAL CONTRL                   ANIMAL CONTROL INSPECTOR      351084.00
19    ANIMAL CONTRL                     ANIMAL CONTROL OFFICER     1192704.00
20    ANIMAL CONTRL                     ANIMAL PLACEMENT COORD      112704.00
21    ANIMAL CONTRL                     ANIMAL SHELTER MANAGER       87564.00
22    ANIMAL CONTRL                  CERTIFIED VETERINARY TECH       56748.00
23    ANIMAL CONTRL                                 DEPUTY DIR      110076.00
24    ANIMAL CONTRL                             DISPATCH CLERK      145788.00
25    ANIMAL CONTRL                EXEC ADMINISTRATIVE ASST II       67800.00
26    ANIMAL CONTRL   EXECUTIVE DIR OF ANIMAL CARE AND CONTROL      135624.00
27    ANIMAL CONTRL                                 STAFF ASST      184200.00
28    ANIMAL CONTRL              SUPERVISING ANIMAL CARE CLERK      104520.00
29    ANIMAL CONTRL          SUPERVISING VETERINARY TECHNICIAN       67800.00
...             ...                                        ...            ...
1703    WATER MGMNT                          MICROBIOLOGIST IV      107208.00
1704    WATER MGMNT              PERSONAL COMPUTER OPERATOR II      135888.00
1705    WATER MGMNT             PERSONAL COMPUTER OPERATOR III       74568.00
1706    WATER MGMNT                         PLUMBING INSPECTOR     2866812.00
1707    WATER MGMNT                     PLUMBING INSPECTOR I/C      337212.00
1708    WATER MGMNT                      PRINCIPAL STOREKEEPER       64860.00
1709    WATER MGMNT                PROCUREMENT CONTROL OFFICER      156408.00
1710    WATER MGMNT                              PROJECT COORD       67800.00
1711    WATER MGMNT                     PROJECTS ADMINISTRATOR      439596.00
1712    WATER MGMNT             SAFETY SPECIALIST - WATER MGMT      614628.00
1713    WATER MGMNT                       SANITARY ENGINEER II      345396.00
1714    WATER MGMNT                      SANITARY ENGINEER III      411540.00
1715    WATER MGMNT                 SENIOR DATA ENTRY OPERATOR       59088.00
1716    WATER MGMNT                 STAFF ASSISTANT - EXCLUDED      143352.00
1717    WATER MGMNT                                 STAFF ASST      363888.00
1718    WATER MGMNT                            STATION LABORER      191598.72
1719    WATER MGMNT             SUPERINTENDENT OF WATER METERS      114528.00
1720    WATER MGMNT                          SUPERVISING CLERK       89808.00
1721    WATER MGMNT          SUPERVISING HOUSE DRAIN INSPECTOR      112404.00
1722    WATER MGMNT       SUPT OF CONSTRUCTION AND MAINTENANCE      258216.00
1723    WATER MGMNT                       SUPVSR OF ACCOUNTING       93924.00
1724    WATER MGMNT                     SUPVSR OF COST CONTROL       98496.00
1725    WATER MGMNT                SUPVSR OF WATER RATE TAKERS       98460.00
1726    WATER MGMNT                           WATER CHEMIST II     1207800.00
1727    WATER MGMNT                          WATER CHEMIST III      430836.00
1728    WATER MGMNT                           WATER CHEMIST IV      321624.00
1729    WATER MGMNT                WATER CONSERVATION ENGINEER      110052.00
1730    WATER MGMNT                       WATER METER ASSESSOR      316680.00
1731    WATER MGMNT                    WATER QUALITY INSPECTOR       64872.00
1732    WATER MGMNT                           WATER RATE TAKER     1514736.00

[1733 rows x 3 columns]

In [7]:
t = total.nlargest(100,'Annual Salary')
t

,Department,Job Titles,Annual Salary
1250,POLICE,POLICE OFFICER,809738772.0
1275,POLICE,SERGEANT,154355892.0
762,FIRE,FIREFIGHTER-EMT,127444212.0
1255,POLICE,POLICE OFFICER (ASSIGNED AS DETECTIVE),110447166.0
772,FIRE,LIEUTENANT-EMT,41825040.0
752,FIRE,FIRE ENGINEER-EMT,35574456.0
1236,POLICE,LIEUTENANT,33784896.0
763,FIRE,FIREFIGHTER-EMT (RECRUIT),32312202.0
777,FIRE,PARAMEDIC,28444746.0
757,FIRE,FIREFIGHTER,27812766.0
1260,POLICE,POLICE OFFICER / FLD TRNG OFFICER,25852728.0
781,FIRE,PARAMEDIC I/C,23068728.0
764,FIRE,FIREFIGHTER/PARAMEDIC,20931126.0
727,FIRE,CAPTAIN-EMT,20014158.0
1173,OEMC,POLICE COMMUNICATIONS OPERATOR II,16474344.0
57,AVIATION,AVIATION SECURITY OFFICER,15274392.0
1216,POLICE,DETENTION AIDE,13780548.0
1172,OEMC,POLICE COMMUNICATIONS OPERATOR I,12577272.0
724,FIRE,BATTALION CHIEF - EMT,11652540.0
771,FIRE,LIEUTENANT,11558766.0
1256,POLICE,POLICE OFFICER (ASSIGNED AS EVIDENCE TECHNICIAN),11366250.0
718,FIRE,AMBULANCE COMMANDER,10347978.0
1358,PUBLIC LIBRARY,LIBRARIAN IV,9230520.0
1355,PUBLIC LIBRARY,LIBRARIAN I,9199596.0
751,FIRE,FIRE ENGINEER,7717314.0
1206,POLICE,COMMANDER,7132656.0
200,BUILDINGS,BUILDING/CONSTRUCTION INSPECTOR,7030836.0
1082,LAW,ASST CORPORATION COUNSEL SUPVSR,6161316.0
1356,PUBLIC LIBRARY,LIBRARIAN II,6017472.0
334,CITY COUNCIL,ALDERMAN,6010500.0
...,...,...,...
44,AVIATION,AIRPORT OPERATIONS SUPVSR I,2296368.0
726,FIRE,CAPTAIN,2290902.0
1183,OEMC,SUPERVISING POLICE COMMUNICATIONS OPERATOR,2277552.0
1374,PUBLIC LIBRARY,SENIOR LIBRARY CLERK,2260680.0
1079,LAW,ASST CORPORATION COUNSEL II,2252196.0
213,BUILDINGS,ELECTRICAL INSPECTOR,2242674.0
1154,OEMC,COMMUNICATIONS OPERATOR I - 311,2241420.0
54,AVIATION,AVIATION COMMUNICATIONS OPERATOR,2214168.0
616,FAMILY & SUPPORT,SUPPORT SERVICES COORD,2203512.0
1166,OEMC,FIRE COMMUNICATIONS OPERATOR I,2203008.0
1085,LAW,CHIEF ASST CORPORATION COUNSEL,2197236.0
1081,LAW,ASST CORPORATION COUNSEL SENIOR,2062008.0
1533,TRANSPORTN,CIVIL ENGINEER IV,2025684.0
1494,STREETS & SAN,PROPERTY CUSTODIAN - AUTO POUND,2008200.0
1425,PUBLIC SAFETY ADMIN,LINEMAN - SALARIED,1999296.0
1635,WATER MGMNT,ASST DISTRICT SUPERINTENDENT,1983696.0
755,FIRE,FIRE MARSHAL-EMT,1946130.0
1254,POLICE,POLICE OFFICER (ASSIGNED AS CANINE HANDLER),1937556.0
1258,POLICE,POLICE OFFICER (ASSIGNED AS TRAFFIC SPECIALIST),1931328.0
504,DAIS,SERVICE WRITER,1902360.0
1203,POLICE,CLERK III,1834968.0
725,FIRE,BATTALION CHIEF-PARAMEDIC,1832508.0
1450,PUBLIC SAFETY ADMIN,TIMEKEEPER - CPD,1801080.0
811,HEALTH,CLINICAL THERAPIST III,1796256.0
1225,POLICE,EXPLOSIVES TECHNICIAN I,1777710.0
1207,POLICE,COMMUNITY ORGANIZER-CAPS,1775484.0
626,FINANCE,ACCOUNTANT IV,1714704.0
547,FAMILY & SUPPORT,ASST COMMUNITY LIVING SPECIALIST,1712028.0
1566,TRANSPORTN,FIELD SERVICE SPECIALIST II,1690560.0
723,FIRE,BATTALION CHIEF,1687560.0

In [8]:
fig1_data = t.pivot(index = 'Department', columns = 'Job Titles', values = 'Annual Salary')
fig1_data

Job Titles,ACCOUNTANT IV,AIRPORT OPERATIONS SUPVSR I,AIRPORT OPERATIONS SUPVSR II,ALDERMAN,AMBULANCE COMMANDER,ASST COMMUNITY LIVING SPECIALIST,ASST CORPORATION COUNSEL I,ASST CORPORATION COUNSEL II,ASST CORPORATION COUNSEL III,ASST CORPORATION COUNSEL SENIOR,...,SENIOR LIBRARY CLERK,SERGEANT,SERVICE WRITER,STAFF ASST TO THE ALDERMAN,STREET LIGHT REPAIR WORKER,SUPERVISING POLICE COMMUNICATIONS OPERATOR,SUPPORT SERVICES COORD,TIMEKEEPER - CPD,TRAFFIC SIGNAL REPAIRMAN,WARD SUPERINTENDENT
Department,,,,,,,,,,,,,,,,,,,,,
AVIATION,NaN,2296368.0,2384904.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BUILDINGS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BUSINESS AFFAIRS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CITY COUNCIL,NaN,NaN,NaN,6010500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6005964.0,NaN,NaN,NaN,NaN,NaN,NaN
COPA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1902360.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FAMILY & SUPPORT,NaN,NaN,NaN,NaN,NaN,1712028.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2203512.0,NaN,NaN,NaN
FINANCE,1714704.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FIRE,NaN,NaN,NaN,NaN,10347978.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HEALTH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LAW,NaN,NaN,NaN,NaN,NaN,NaN,3690348.0,2252196.0,4651680.0,2062008.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OEMC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2277552.0,NaN,NaN,NaN,NaN
POLICE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,154355892.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PUBLIC LIBRARY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2260680.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PUBLIC SAFETY ADMIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1801080.0,NaN,NaN
STREETS & SAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4617204.0
TRANSPORTN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3887520.0,NaN,NaN,NaN,2887872.0,NaN
WATER MGMNT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
dept = fig1_data.index.values.tolist()
dept

['AVIATION',
 'BUILDINGS',
 'BUSINESS AFFAIRS',
 'CITY COUNCIL',
 'COPA',
 'DAIS',
 'FAMILY & SUPPORT',
 'FINANCE',
 'FIRE',
 'HEALTH',
 'LAW',
 'OEMC',
 'POLICE',
 'PUBLIC LIBRARY',
 'PUBLIC SAFETY ADMIN',
 'STREETS & SAN',
 'TRANSPORTN',
 'WATER MGMNT']

In [10]:
converse = t.pivot(index = 'Job Titles', columns = 'Department', values = 'Annual Salary')
job = converse.index.values.tolist()
job

['ACCOUNTANT IV',
 'AIRPORT OPERATIONS SUPVSR I',
 'AIRPORT OPERATIONS SUPVSR II',
 'ALDERMAN',
 'AMBULANCE COMMANDER',
 'ASST COMMUNITY LIVING SPECIALIST',
 'ASST CORPORATION COUNSEL I',
 'ASST CORPORATION COUNSEL II',
 'ASST CORPORATION COUNSEL III',
 'ASST CORPORATION COUNSEL SENIOR',
 'ASST CORPORATION COUNSEL SUPVSR',
 'ASST DISTRICT SUPERINTENDENT',
 'ASST TO THE ALDERMAN',
 'AVIATION COMMUNICATIONS OPERATOR',
 'AVIATION SECURITY OFFICER',
 'AVIATION SECURITY SERGEANT',
 'BATTALION CHIEF',
 'BATTALION CHIEF - EMT',
 'BATTALION CHIEF-PARAMEDIC',
 'BRIDGE OPERATOR',
 'BUILDING/CONSTRUCTION INSPECTOR',
 'BUSINESS COMPLIANCE INVESTIGATOR',
 'CAPTAIN',
 'CAPTAIN-EMT',
 'CHIEF ASST CORPORATION COUNSEL',
 'CIVIL ENGINEER IV',
 'CLERK III',
 'CLINICAL THERAPIST III',
 'COMMANDER',
 'COMMUNICABLE DISEASE CONTROL INVESTIGATOR II',
 'COMMUNICATIONS OPERATOR I - 311',
 'COMMUNITY ORGANIZER-CAPS',
 'DEPUTY CHIEF',
 'DEPUTY CORPORATION COUNSEL',
 'DEPUTY DISTRICT CHIEF',
 'DETENTION AIDE',
 'ELECTRICAL INSPECTOR',
 'EXPLOSIVES TECHNICIAN I',
 'FIELD SERVICE SPECIALIST II',
 'FIRE COMMUNICATIONS OPERATOR I',
 'FIRE COMMUNICATIONS OPERATOR II',
 'FIRE ENGINEER',
 'FIRE ENGINEER-EMT',
 'FIRE ENGINEER-PARAMEDIC',
 'FIRE MARSHAL-EMT',
 'FIREFIGHTER',
 'FIREFIGHTER (PER ARBITRATORS AWARD)-EMT',
 'FIREFIGHTER (PER ARBITRATORS AWARD)-PARAMEDIC',
 'FIREFIGHTER-EMT',
 'FIREFIGHTER-EMT (RECRUIT)',
 'FIREFIGHTER/PARAMEDIC',
 'HEAD LIBRARY CLERK',
 'INVESTIGATOR-COPA',
 'LEGISLATIVE AIDE',
 'LIBRARIAN I',
 'LIBRARIAN II',
 'LIBRARIAN III',
 'LIBRARIAN IV',
 'LIBRARY ASSOCIATE',
 'LIBRARY CLERK',
 'LIEUTENANT',
 'LIEUTENANT-EMT',
 'LIEUTENANT-PARAMEDIC',
 'LINEMAN - SALARIED',
 'PARALEGAL II',
 'PARAMEDIC',
 'PARAMEDIC FIELD CHIEF',
 'PARAMEDIC I/C',
 'PARKING ENFORCEMENT AIDE',
 'PLUMBING INSPECTOR',
 'POLICE ADMINISTRATIVE CLERK',
 'POLICE COMMUNICATIONS OPERATOR I',
 'POLICE COMMUNICATIONS OPERATOR II',
 'POLICE OFFICER',
 'POLICE OFFICER (ASGND AS MARINE OFFICER)',
 'POLICE OFFICER (ASSIGNED AS CANINE HANDLER)',
 'POLICE OFFICER (ASSIGNED AS DETECTIVE)',
 'POLICE OFFICER (ASSIGNED AS EVIDENCE TECHNICIAN)',
 'POLICE OFFICER (ASSIGNED AS TRAFFIC SPECIALIST)',
 'POLICE OFFICER / FLD TRNG OFFICER',
 'POLICE OFFICER/EXPLSV DETECT K9 HNDLR',
 'PROPERTY CUSTODIAN - AUTO POUND',
 'PUBLIC HEALTH NURSE II',
 'REFUSE COLLECTION COORD',
 'SANITARIAN II',
 'SANITATION CLERK',
 'SENIOR DATA ENTRY OPERATOR',
 'SENIOR LIBRARY CLERK',
 'SERGEANT',
 'SERVICE WRITER',
 'STAFF ASST TO THE ALDERMAN',
 'STREET LIGHT REPAIR WORKER',
 'SUPERVISING POLICE COMMUNICATIONS OPERATOR',
 'SUPPORT SERVICES COORD',
 'TIMEKEEPER - CPD',
 'TRAFFIC SIGNAL REPAIRMAN',
 'WARD SUPERINTENDENT']

In [11]:
total2 = salary.groupby(['Department','Job Titles','Name'],as_index =False)['Annual Salary'].sum()
total2

,Department,Job Titles,Name,Annual Salary
0,ADMIN HEARNG,ADMINISTRATIVE ASST II,"CHAVEZ, STEPHANIE G",48600.0
1,ADMIN HEARNG,ADMINISTRATIVE ASST II,"CORNELL, LYNETTE C",61956.0
2,ADMIN HEARNG,ADMINISTRATIVE ASST II,"DANIELS, MARIA R",46428.0
3,ADMIN HEARNG,ADMINISTRATIVE ASST II,"FLOURNOY, NICOLE A",74568.0
4,ADMIN HEARNG,ADMINISTRATIVE ASST II,"GREEN, CAROLYN",74568.0
5,ADMIN HEARNG,ADMINISTRATIVE ASST II,"HADDAD, ISSA A",42960.0
6,ADMIN HEARNG,ADMINISTRATIVE ASST II,"HEARAN, KARIN D",74568.0
7,ADMIN HEARNG,ADMINISTRATIVE ASST II,"JONES, LOIS M",74568.0
8,ADMIN HEARNG,ADMINISTRATIVE ASST II,"MC KINNEY, TERESA M",74568.0
9,ADMIN HEARNG,ADMINISTRATIVE ASST II,"MCCOLLUM, LITITIA",42960.0
10,ADMIN HEARNG,ADMINISTRATIVE ASST II,"PARKER, CHALINE D",74568.0
11,ADMIN HEARNG,ADMINISTRATIVE ASST II,"ROBINS, DENISE D",74568.0
12,ADMIN HEARNG,ADMINISTRATIVE ASST II,"SEPULVEDA CORY, LORI J",74568.0
13,ADMIN HEARNG,ADMINISTRATIVE ASST II,"SIMPSON, KAREN E",71220.0
14,ADMIN HEARNG,ADMINISTRATIVE ASST II,"STREET, FREDDIE M",42960.0
15,ADMIN HEARNG,ADMINISTRATIVE ASST II,"TADEO, ALITA F",67944.0
16,ADMIN HEARNG,ADMINISTRATIVE ASST II,"WHEATLEY, DELLA",56448.0
17,ADMIN HEARNG,ADMINISTRATIVE ASST III,"CASSELLA, CATHERINE",74568.0
18,ADMIN HEARNG,ADMINISTRATIVE ASST III,"ERVING, WILGENIA B",85704.0
19,ADMIN HEARNG,ADMINISTRATIVE ASST III,"ESPINOSA, YVONNE",78120.0
20,ADMIN HEARNG,ADMINISTRATIVE ASST III,"WILSON, CASSANDRA M",61332.0
21,ADMIN HEARNG,ADMINISTRATIVE SERVICES OFFICER II EXCLD,"RIZZO, MARGARET A",96096.0
22,ADMIN HEARNG,ADMINISTRATIVE SUPVSR,"HESTER, DEBORAH A",72744.0
23,ADMIN HEARNG,CUSTOMER ACCOUNT REPRESENTATIVE,"BURAGE, LORRIE A",64872.0
24,ADMIN HEARNG,DEPUTY DIR OF ADMINISTRATIVE ADJUDICATION,"RIZZO, ANTHONY J",135624.0
25,ADMIN HEARNG,DIR OF ADMINISTRATION I,"COCO, MICHELLE T",96096.0
26,ADMIN HEARNG,DIR OF ADMINISTRATIVE HEARINGS,"JACKOWIAK, PATRICIA",161112.0
27,ADMIN HEARNG,EXEC ADMINISTRATIVE ASST II,"TAKATA, NANCY M",72744.0
28,ADMIN HEARNG,FISCAL ADMINISTRATOR,"HENNIGAN, KEVIN G",121188.0
29,ADMIN HEARNG,MANAGER OF ADMINSTRATIVE ADJUDICATION,"BURTIN-COX, DATOYA J",100620.0
...,...,...,...,...
25450,WATER MGMNT,WATER CHEMIST III,"HO, NAM C",73200.0
25451,WATER MGMNT,WATER CHEMIST III,"LOJA, HECTOR A",73200.0
25452,WATER MGMNT,WATER CHEMIST III,"SIDDIQUI, ABDURRAZZAQ",98292.0
25453,WATER MGMNT,WATER CHEMIST IV,"JACOB, LOVELY",107208.0
25454,WATER MGMNT,WATER CHEMIST IV,"JULION, JIMMIE L",107208.0
25455,WATER MGMNT,WATER CHEMIST IV,"WASHINGTON, JOSEPH",107208.0
25456,WATER MGMNT,WATER CONSERVATION ENGINEER,"HO, KWOK L",110052.0
25457,WATER MGMNT,WATER METER ASSESSOR,"ESPINOSA, RODOLFO",89772.0
25458,WATER MGMNT,WATER METER ASSESSOR,"GARCIA, SALVADOR",64224.0
25459,WATER MGMNT,WATER METER ASSESSOR,"O NEAL, ROZELLA",98460.0
25460,WATER MGMNT,WATER METER ASSESSOR,"PUGHSLEY, KENNETH",64224.0
25461,WATER MGMNT,WATER QUALITY INSPECTOR,"MACIEL, SANDRA M",64872.0
25462,WATER MGMNT,WATER RATE TAKER,"ALVAREZ, JUAN D",64224.0
25463,WATER MGMNT,WATER RATE TAKER,"BAKER, SHAWANDA S",64224.0
25464,WATER MGMNT,WATER RATE TAKER,"BOLTON, BRIAN E",89772.0
25465,WATER MGMNT,WATER RATE TAKER,"BROWN, SHARON L",98460.0
25466,WATER MGMNT,WATER RATE TAKER,"DIAZ, OSCAR A",98460.0
25467,WATER MGMNT,WATER RATE TAKER,"GREEN, JACQUELINE E",64224.0
25468,WATER MGMNT,WATER RATE TAKER,"HEDRICK, LEE A",89772.0
25469,WATER MGMNT,WATER RATE TAKER,"JOHNSON, CURTIS V",89772.0
25470,WATER MGMNT,WATER RATE TAKER,"KORDOWSKI, ANTHONY",98460.0
25471,WATER MGMNT,WATER RATE TAKER,"MUNOZ, JUDY L",64224.0
25472,WATER MGMNT,WATER RATE TAKER,"MURPHY, TROSLYN S",64224.0
25473,WATER MGMNT,WATER RATE TAKER,"POWERS, MICHAEL R",64224.0
25474,WATER MGMNT,WATER RATE TAKER,"RIOS, FRANCISCO",89772.0
25475,WATER MGMNT,WATER RATE TAKER,"SIMS, DEMETRIUS",98460.0
25476,WATER MGMNT,WATER RATE TAKER,"SMITH, NANCY A",98460.0
25477,WATER MGMNT,WATER RATE TAKER,"TATE, GARY",98460.0
25478,WATER MGMNT,WATER RATE TAKER,"TIGNOR, DARRYL B",89772.0
25479,WATER MGMNT,WATER RATE TAKER,"VELAZQUEZ, JOHN",89772.0

In [12]:
# CREATE LABEL - #1
mySelectedLabel = ipywidgets.Label()

In [13]:
# CREATE HEATMAP ELEMENTS - #2
# scales
col_sc = bqplot.ColorScale(scheme="Red")
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()

# axis
c_ax = bqplot.ColorAxis(scale = col_sc, orientation = 'vertical', side = 'right')
x_ax = bqplot.Axis(scale = x_sc, label = 'Job Titles')
y_ax = bqplot.Axis(scale = y_sc, orientation='vertical', label = 'Department')

# marks
heat_map = bqplot.GridHeatMap(color=fig1_data, 
                              scales ={'color':col_sc, 'row': y_sc, 'column': x_sc}, 
                             interactions={'click':'select'}, # an interaction associated with GHM
                             anchor_style = {'fill':'blue'}) 

# create the grid heat map
fig = bqplot.Figure(marks=[heat_map], axes = [c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Red'), side='right'), Axis(label='Job …

In [14]:
# CREATE SCATTER PLOT ELEMENTS - #3
# scales
x_sch = bqplot.OrdinalScale() # range of data along Z -axis => 0->1
y_sch = bqplot.LinearScale() # frequency, counts

# axis
x_axh = bqplot.Axis(scale = x_sch, label='Name')
y_axh = bqplot.Axis(scale = y_sch, 
                   orientation='vertical',
                   label = 'Annual Salary')

# marks
# a sample dataset used for sample scatter plot
sample =  total2[(total2['Department'] == 'ADMIN HEARNG') & (total2['Job Titles'] == 'ADMINISTRATIVE ASST II')]

hist = bqplot.Scatter(x = sample['Name'], y = sample['Annual Salary'], scales={'x':x_sch, 'y':y_sch})

# create the scatter plot
fig_hist = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])
fig_hist

Figure(axes=[Axis(label='Name', scale=OrdinalScale()), Axis(label='Annual Salary', orientation='vertical', sca…

In [15]:
# LINKING SCATTER PLOT WITH HEATMAP
def on_selected(change):
    if len(change['owner'].selected) == 1: # only selecting 1 element at a time
        i,j = change['owner'].selected[0] # y & x indicies
        v = fig1_data.at[dept[i],job[j]] # x, y indicies, grab data value at this location
        mySelectedLabel.value = 'Annual Salary = ' + str(v) # update widget label with this value
        
        # link the scatter plot
        s = total2[(total2['Department'] == dept[i]) & (total2['Job Titles'] == job[j])]
        hist.x = s['Name']
        hist.y = s['Annual Salary']

# make sure we "observe" for a change in our heatmap (traitlets)
heat_map.observe(on_selected, 'selected')

In [16]:
# layout - nested HBox & VBox
figures = ipywidgets.HBox([fig, fig_hist])

# change how big my figures appear on my output
fig.layout.min_width='400px'
fig_hist.layout.min_width='400px'

# dashboard
myDashboard = ipywidgets.VBox([mySelectedLabel, figures])
myDashboard

VBox(children=(Label(value=''), HBox(children=(Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale…

The main purpose of this dashboard is to visually characterize the total annual salary of different jobs in each department and the distribution of the total annual salary of each employee under each job. The left component is a grid heat map.I chose salary paid employees in particular, because only them has annual salary. Then I grouped the dataset by department and job titles to get the sum of annual salary.I also selected the top 100 annual salary as the original data, because the entire dataset has too much data，which could not be displayed in the heat map.Then I created a pivot table based on the previous "groupby" dataframe. This pivot table could be used as "color" data when I create the heatmap. The right component is a scatter plot.I grouped the dataset by department, job titles, and especially，employee names (which indicated employee' total annual salary grouped by departments and jobs). Then I picked a smaple dataset for the sample scatter plot. For the linking step, I draged out the "department" and "job titles" column qas a list to give them a specific number to indicate changes. When we click on a grid, its coordinate( x represents job titles number, y represents department number) could be used to update the total annual salary value as well as the "Annual salary - Name" plot.By looking at the distribution of employee salaries (the salary level of most employees, the number of high- or low-paid employees, etc.), we could analyze whether the salary distribution of each department and job title is reasonable.

One contextual dataset: "2020_Budget_Recommendations - Positions_and_Salaries".
I obtained this dataset from the City of Chicago data portal.

URL: https://data.cityofchicago.org/Administration-Finance/Budget-2020-Budget-Recommendations-Positions-and-S/j6b9-brjc

This data set is excerpted from the 2020 municipal government budget proposal and mainly contains the 2020 salary budget by department and job title. This dataset could be used to compare the difference between budget and actual salary.